let
    CalendarTable = (StartDate as date, EndDate as date) as table =>
let
    DaysInterval = Duration.Days(EndDate - StartDate),
    DatesList = List.Dates (StartDate, DaysInterval, #duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(DatesList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Date"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Quarter", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted First Characters" = Table.AddColumn(#"Inserted Month Name", "First Characters", each Text.Start([Month Name], 3), type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted First Characters", "Merged", each Text.Combine({"Q", Text.From([Quarter], "en-IN")}), type text),
    #"Inserted Merged Column1" = Table.AddColumn(#"Inserted Merged Column", "Merged.1", each Text.Combine({[First Characters], "-", Text.From([Year], "en-IN")}), type text),
    #"Inserted Merged Column2" = Table.AddColumn(#"Inserted Merged Column1", "Merged.2", each Text.Combine({[Merged], "-", Text.From([Year], "en-IN")}), type text),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Merged Column2",{{"Quarter", "QuarterNumber"}, {"Month", "MonthNumber"}, {"Month Name", "Long Month Name"}, {"First Characters", "Month"}, {"Merged", "Quarter"}, {"Merged.1", "Month-Year"}, {"Merged.2", "Quarter-Year"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Month-YearSort", each if [MonthNumber] <= 9 then 
Number.ToText([Year])&"0"&Number.ToText([MonthNumber]) else
Number.ToText([Year])&Number.ToText([MonthNumber])),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Quarter-YearSort", each Number.ToText([Year])&"0"&Number.ToText([QuarterNumber])),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom1",{"Date", "Year", "QuarterNumber", "MonthNumber", "Long Month Name", "Month", "Quarter", "Month-Year", "Month-YearSort", "Quarter-Year", "Quarter-YearSort"}),
    #"Changed Type 2" = Table.TransformColumnTypes(#"Reordered Columns",{{"Month-YearSort", Int64.Type}, {"Quarter-YearSort", Int64.Type}})
in
    #"Changed Type 2"
in
    CalendarTable
